name: kisi_st2u_example
description: Example app demonstrating the kisi_st2u Flutter plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  kisi_st2u:
    path: ../

flutter:
  uses-material-design: true
